# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='travel_time',
            field=models.IntegerField(verbose_name='Время в пути'),
        ),
    ]
