# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0003_auto_20180301_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название маршрута')),
                ('travel_time', models.IntegerField(verbose_name='Время в пути')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='begin', to='cities.City', verbose_name='Откуда')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end', to='cities.City', verbose_name='Куда')),
                ('trouth_cities', models.ManyToManyField(blank=True, related_name='trouth_cities', to='cities.City', verbose_name='Через города')),
            ],
            options={
                'verbose_name_plural': 'Маршруты',
                'ordering': ['name'],
                'verbose_name': 'Маршрут',
            },
        ),
    ]
