# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название маршрута')),
                ('from_city', models.CharField(max_length=50, verbose_name='Откуда')),
                ('to_city', models.CharField(max_length=50, verbose_name='Куда')),
                ('travel_time', models.IntegerField(verbose_name='Время в пути')),
                ('trouth_cities', models.ManyToManyField(blank=True, to='trains.Train', verbose_name='Через города')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Маршруты',
                'verbose_name': 'Маршрут',
            },
        ),
    ]
