# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='from_city',
            field=models.CharField(max_length=50, verbose_name='Откуда'),
        ),
        migrations.AlterField(
            model_name='route',
            name='to_city',
            field=models.CharField(max_length=50, verbose_name='Куда'),
        ),
        migrations.AlterField(
            model_name='route',
            name='trouth_cities',
            field=models.ManyToManyField(blank=True, to='trains.Train', verbose_name='Через города'),
        ),
    ]
