# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Населенный пункт', 'verbose_name_plural': 'Населенный пункт'},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Населенный пункт'),
        ),
    ]
