# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_auto_20180228_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Населенный пункт', 'verbose_name_plural': 'Населенные пункты'},
        ),
    ]
